import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from 'react';
import { getLeaderboard } from '../lib/auth';
import { useAuth } from '../context/AuthContext';
import { Trophy } from 'lucide-react';
export default function Leaderboard() {
    const { user } = useAuth();
    const [data, setData] = useState([]);
    useEffect(() => {
        getLeaderboard().then(setData);
        const t = setInterval(() => getLeaderboard().then(setData), 10000);
        return () => clearInterval(t);
    }, []);
    const medals = ['🥇', '🥈', '🥉'];
    const fmt = (n) => n.toLocaleString('de-DE');
    return (_jsxs("div", { className: "gp", style: { maxWidth: 900 }, children: [_jsxs("div", { className: "afu", style: { marginBottom: 28 }, children: [_jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: 12, marginBottom: 6 }, children: [_jsx(Trophy, { size: 24, color: "var(--gold)" }), _jsx("h1", { className: "tg playfair", style: { fontSize: 28, fontWeight: 900 }, children: "Leaderboard" })] }), _jsx("p", { style: { color: 'var(--text2)', fontSize: 14 }, children: "Top players ranked by total profit \u00B7 Updates every 10s" })] }), data.length === 0 ? (_jsxs("div", { className: "card-flat", style: { padding: 48, textAlign: 'center' }, children: [_jsx(Trophy, { size: 40, color: "var(--text2)", style: { margin: '0 auto 14px' } }), _jsx("p", { style: { color: 'var(--text2)', fontSize: 15 }, children: "No players yet. Be the first to play!" })] })) : (_jsxs("div", { children: [_jsx("div", { style: { display: 'grid', gridTemplateColumns: '40px 1fr 110px 110px 90px', gap: 8, padding: '8px 16px', marginBottom: 6 }, children: ['#', 'Player', 'Profit', 'Won', 'Games'].map(h => (_jsx("span", { style: { fontSize: 10, fontWeight: 600, letterSpacing: '.1em', textTransform: 'uppercase', color: 'var(--text2)' }, children: h }, h))) }), _jsx("div", { style: { display: 'flex', flexDirection: 'column', gap: 4 }, children: data.map((p, i) => {
                            const isMe = p.username === user?.username;
                            return (_jsxs("div", { className: `lb-row afu ${i === 0 ? 'top1' : i === 1 ? 'top2' : i === 2 ? 'top3' : ''}`, style: { animationDelay: `${i * .04}s`, animationFillMode: 'both', opacity: 0, border: isMe ? '1px solid rgba(201,168,76,.4)' : undefined, background: isMe ? 'rgba(201,168,76,.08)' : undefined }, children: [_jsx("div", { style: { fontSize: 18, textAlign: 'center' }, children: i < 3 ? medals[i] : _jsxs("span", { style: { fontSize: 13, color: 'var(--text2)', fontWeight: 600 }, children: ["#", i + 1] }) }), _jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: 10 }, children: [_jsx("div", { style: { width: 32, height: 32, borderRadius: '50%', background: 'linear-gradient(135deg,var(--gold-d),var(--gold))', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13, fontFamily: 'Playfair Display', fontWeight: 700, color: '#1a0e00', flexShrink: 0 }, children: p.username.charAt(0).toUpperCase() }), _jsxs("div", { children: [_jsxs("p", { style: { fontSize: 14, fontWeight: 600, color: isMe ? 'var(--gold)' : 'var(--text1)' }, children: [p.username, isMe && _jsx("span", { style: { fontSize: 9, padding: '1px 6px', borderRadius: 10, background: 'rgba(201,168,76,.15)', color: 'var(--gold)', marginLeft: 6 }, children: "YOU" })] }), _jsxs("p", { style: { fontSize: 11, color: 'var(--text2)' }, children: [p.games_played, " games"] })] })] }), _jsxs("div", { children: [_jsxs("p", { style: { fontSize: 14, fontWeight: 700, fontFamily: 'Playfair Display', color: p.profit >= 0 ? 'var(--green)' : 'var(--red)' }, children: [p.profit >= 0 ? '+' : '', fmt(p.profit)] }), _jsx("p", { style: { fontSize: 10, color: 'var(--text2)' }, children: "coins" })] }), _jsxs("div", { children: [_jsxs("p", { style: { fontSize: 13, fontWeight: 600, color: 'var(--green)' }, children: ["+", fmt(p.total_won)] }), _jsx("p", { style: { fontSize: 10, color: 'var(--text2)' }, children: "won" })] }), _jsxs("div", { children: [_jsx("p", { style: { fontSize: 13, fontWeight: 600, color: 'var(--gold)' }, children: fmt(p.balance) }), _jsx("p", { style: { fontSize: 10, color: 'var(--text2)' }, children: "balance" })] })] }, p.username));
                        }) })] }))] }));
}
